In [6]:
import pandas as pd

In [7]:
# read csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [8]:
# show df
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 1 Selecting with a single value

## loc[row_label, column_label]

In [9]:
# get all data about L.Messi
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [10]:
# get the height of L.Messi
df.loc['L. Messi', 'height_cm']

np.int64(170)

In [11]:
# get the weight of Cristiano Ronaldo
df.loc['Cristiano Ronaldo', 'weight_kg']

np.int64(83)

In [12]:
# get all rows inside the 'height_cm' column
df.loc[:, 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [13]:
# get all columns that correspond to the index 'L. Messi'
df.loc['L. Messi', :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [14]:
# the same tasks for 29.09

# 2 Selecting with a list of values

In [15]:
# get all data about L. Messi and Cristiano Ronaldo
df.loc[['L. Messi', 'Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [19]:
# get the height of L. Messi and Cristiano Ronaldo
df.loc[['L. Messi', 'Cristiano Ronaldo'], 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [21]:
# get the height and weight of L. Messi
df.loc['L. Messi', ['height_cm', 'weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: int64

In [20]:
# get height and weight of L. Messi and Cristiano Ronaldo
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm', 'weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## 3 Selecting a range of data with a slice

start:stop:step (Note that contary to usual python slices, both the start and the stop are included)

In [33]:
# slice column labels
players = ['L. Messi', 'Cristiano Ronaldo']

df.loc[players, 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [38]:
# slice index labels
columns = ['age', 'dob', 'height_cm', 'weight_kg']

# get top1 and top10 player name
df.index[:10]

df.loc['L. Messi':'M. Salah', columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

## 4 Selecting with conditions

In [42]:
# one condition: select player with height above 180cm
columns = ['age', 'dob', 'height_cm', 'weight_kg']
df.loc[df['height_cm']>180]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [54]:
# multiple conditions: select player with height above 180cm from Argentina
df.loc[(df['height_cm']>190) & (df['nationality']=='Argentina'), :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
E. Andrada,Esteban Andrada,28,1991-01-26,194,81,Argentina,Boca Juniors
W. Benítez,Walter Benítez,26,1993-01-19,191,91,Argentina,OGC Nice
S. Romero,Sergio Germán Romero,32,1987-02-22,192,86,Argentina,Manchester United
F. Fazio,Federico Julián Fazio,32,1987-03-17,195,85,Argentina,Roma
N. Guzmán,Nahuel Ignacio Guzmán,33,1986-02-10,193,94,Argentina,Tigres U.A.N.L.
J. Musso,Juan Musso,25,1994-05-06,191,93,Argentina,Udinese
A. Donatti,Alejandro Donatti,32,1986-10-24,192,86,Argentina,Racing Club
R. Civelli,Renato Civelli,35,1983-10-14,195,89,Argentina,Club Atlético Banfield
A. Barboza,Alexander Nahuel Barboza Ullúa,24,1995-03-16,192,88,Argentina,Independiente
G. Conti,Germán Andrés Conti,25,1994-06-03,194,80,Argentina,SL Benfica
E. Martínez,Emiliano Martínez,26,1992-09-02,193,85,Argentina,Arsenal
P. Gazzaniga,Paulo Dino Gazzaniga,27,1992-01-02,196,90,Argentina,Tottenham Hotspur
G. Carrillo,Guido Carrillo,28,1991-05-25,191,87,Argentina,Southampton
A. Rossi,Agustín Daniel Rossi,23,1995-08-21,193,95,Argentina,Club Atlético Lanús
C. Lema,Cristian Lema,29,1990-03-24,191,90,Argentina,Newell's Old Boys
M. Andújar,Mariano Gonzalo Andújar,35,1983-07-30,194,86,Argentina,Estudiantes de La Plata
N. Spolli,Nicolás Federico Spolli,36,1983-02-20,193,90,Argentina,Crotone
S. García,Santiago García,30,1988-07-08,191,88,Argentina,Deportivo Toluca
M. Dituro,Matías Dituro,32,1987-05-08,191,90,Argentina,Universidad Católica
L. Pocrnjic,Luciano Darío Pocrnjic,37,1981-08-04,192,86,Argentina,Club Atlético Aldosivi
N. Navarro,Nicolás Gastón Navarro,34,1985-03-25,191,87,Argentina,San Lorenzo de Almagro
J. Schunke,Jonathan Schunke,32,1987-02-22,193,86,Argentina,Estudiantes de La Plata
E. Rescaldani,Ezequiel Rescaldani,27,1992-06-11,191,83,Argentina,Arsenal de Sarandí
A. Werner,Axel Werner,23,1996-02-28,191,85,Argentina,Atlético de San Luis
N. Paz,Nehuén Mario Paz,27,1992-04-28,191,89,Argentina,Bologna
G. Peñalba,Gabriel Martín Peñalba,34,1984-09-23,194,90,Argentina,Tiburones Rojos de Veracruz
M. Quiroga,Mauro Quiroga,29,1989-12-07,191,87,Argentina,Club Necaxa
S. Vergini,Santiago Vergini,30,1988-08-03,191,83,Argentina,San Lorenzo de Almagro
L. Acevedo,Lucas Acevedo,27,1991-11-08,197,97,Argentina,Club Atlético Colón
G. Campi,Gastón Campi,28,1991-04-06,193,88,Argentina,Trabzonspor
T. Figueroa,Tobías Figueroa,27,1992-02-04,191,90,Argentina,CD Antofagasta
D. Novaretti,Diego Martín Novaretti,34,1985-05-09,193,91,Argentina,Rosario Central
F. Pellegrino,Fernando Pellegrino,33,1986-03-31,197,90,Argentina,Club Atlético Huracán
M. Guanini,Manuel Guanini,23,1996-02-14,191,86,Argentina,Gimnasia y Esgrima La Plata
R. Noya,Rodrigo Javier Noya García,29,1990-01-31,194,80,Argentina,Club Necaxa
D. Sappa,Daniel Sappa,24,1995-02-09,193,90,Argentina,Arsenal de Sarandí
N. Avellaneda,Nicolás Gastón Avellaneda,26,1993-02-24,191,83,Argentina,Defensa y Justicia
L. Nequecaur,Luciano Nequecaur,26,1992-07-19,192,87,Argentina,Clube Sport Marítimo
J. Pourtau,Jerónimo Pourtau,19,2000-01-23,193,87,Argentina,Estudiantes de La Plata
L. Merolla,Lucas Gabriel Merolla,24,1995-06-27,193,85,Argentina,Club Atlético Huracán
M. Centurión,Maximiliano Centurión,21,1998-01-01,193,91,Argentina,Argentinos Juniors
J. Blazquez,Joaquin Blazquez,19,2000-01-28,192,83,Argentina,Valencia CF