In [1]:
import pandas as pd

# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1 Rename Column

In [4]:
# rename column and overwrite values of the dataframe
df_exams.rename(columns={'gender':'Gender'}, inplace=True)
df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
# rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'math score':'MS', 
                         'reading score': 'RS', 
                         'writing score':'WS'
                        }, inplace=True)

In [8]:
# show dataframe
df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 2 Rename Index

In [10]:
# rename index 0, 1 and 2 and update the DF
df_exams.rename(index={0: 'A', 1: 'B', 2: 'C'}, inplace=True)

In [11]:
# show first 3 rows
df_exams.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
A,female,group B,bachelor's degree,standard,none,72,72,74
B,female,group C,some college,standard,completed,69,90,88
C,female,group B,master's degree,standard,none,90,95,93