# Python basics (I know probably 95% of this info, but repeat is not bad😄)

## Hello world

In [8]:
print('Hello world!', end=4 * "\n")

Hello world!

In [9]:
countries = ['USA', 'India', 'China', 'Brazil']

In [10]:
countries

['USA', 'India', 'China', 'Brazil']

## Module

In [11]:
 import os

In [12]:
os.getcwd()

'C:\\Users\\razma'

# Pandas 🐼

In [2]:
import numpy as np
import pandas as pd

## 1. Creating a dataframe from an array

### 1.1 Option 1

In [14]:
# creating an array
data = np.array([[1,10], [2, 15], [3, 1111]])

In [15]:
# creating a dataframe
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'], 
             columns=['col1', 'col2']
            )

In [16]:
# showing the dataframe
df

      col1  col2
row1     1    10
row2     2    15
row3     3  1111

### 1.2 Option 2

In [17]:
# creating an array with list shape
data = [[1,10], [2, 15], [3, 1111]]

In [18]:
# creating a dataframe
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'], 
             columns=['col1', 'col2']
            )

In [19]:
df

      col1  col2
row1     1    10
row2     2    15
row3     3  1111

## 2. Creating a dataframe from a dictionary

In [20]:
# lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [123213123, 33333333, 122333333, 66664433]

In [21]:
# Storing lists within a dictionary
dict_states = {'States': states, 'Population': population}

In [22]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [23]:
# showing the dataframe
df_population

       States  Population
0  California   123213123
1       Texas    33333333
2     Florida   122333333
3    New York    66664433

## 3. Creating a DataFrame from a csv file

In [3]:
# reading the csv file
# import os
# print(os.getcwd())
df_exams = pd.read_csv("StudentsPerformance.csv")

In [25]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [26]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [27]:
# show last 5 rows in a dataframe
df_exams.tail(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [29]:
# show last n rows in a dataframe
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [43]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [47]:
# display n rows
pd.set_option('display.max_rows', 10)

In [48]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')